# Generated by Django 4.1.3 on 2022-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_group_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
